# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up private settings example
        run: mv ./src/privatesettings.ts.example.txt ./src/privatesettings.ts

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        
      - name: Beanstalk Deploy
        # You may pin to the exact commit or the version.
        # uses: einaregilsson/beanstalk-deploy@6f594ded1b0a22c5e5aa1088e7c58dc5816c92ea
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          # AWS Access Key
          aws_access_key: 
          # AWS Secret Key
          aws_secret_key: 
          # AWS Session Token when using temporary security credentials such as when assuming a role in AWS through STS
          aws_session_token: # optional
          # AWS Region
          region: 
          # Beanstalk application name
          application_name: 
          # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
          environment_name: # optional
          # Version label for new Beanstalk version
          version_label: 
          # Version description for the new Beanstalk version
          version_description: # optional
          # Zip file with the version to deploy. If skipped the action will deploy existing version.
          deployment_package: # optional
          # Whether the action should skip creating a new bucket and use the given one to upload the deployment package to instead. When omitted the actions will (try to) create a new one during deployment.
          existing_bucket_name: # optional
          # If set to "true" then the action will deploy an existing version with the given version_label if it already exists, but otherwise create the version and deploy it. If set to true for an action with no environment name it will upload a version if it does not exist already, but do nothing if the version already exists.
          use_existing_version_if_available: # optional
          # Whether the action should wait for the deployment to finish and log status messages during the wait. Default is "true". If set to "false" the action will start the deployment on Beanstalk and then exit.
          wait_for_deployment: # optional
          # How many seconds to wait for the environment to return to Green state after deployment is finished. Default is 30 seconds.
          wait_for_environment_recovery: # optional
